backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Header", name: "header", widget: "string" }
          - { label: "Content", name: "content", widget: "string" }
