backend:
  name: test-repo
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Landing Page About Section"
        name: "landing-about"
        file: "content/landing-about.md"
        fields:
          - { label: "Header", name: "header", widget: "string" }
          - { label: "Content", name: "content", widget: "string" }
      - label: "Upcoming Concerts"
        name: "upcoming-concerts"
        file: "content/upcoming-concerts.md"
        widget: list
        fields:
          - { label: "Title", name: "title", widget: string }
          - { label: "Date and Time", name: "datetime", widget: datetime }
          - { label: "Address", name: "address", widget: "string" }
          - { label: "Ticket Link", name: "ticketLink", widget: string }
      - label: "About Page"
        name: "landing-about"
        file: "content/landing-about.md"
        widget: list
        fields:
          - { label: "Header", name: "header", widget: "string" }
          - { label: "Content", name: "content", widget: "string" }
