backend:
  name: git-gateway
  branch: main

media_folder: public/img
public_folder: img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Hero"
        name: "hero"
        file: "content/hero.md"
        fields:
          - label: "Header"
            name: "header"
            widget: "string"
          - label: "Sub-Header"
            name: "subHeader"
            widget: "string"
          - label: "Background Image"
            name: "backgroundImage"
            widget: "image"
      - label: "Biography"
        name: "biography"
        file: "content/biography.md"
        fields:
          - label: "Header"
            name: "header"
            widget: "string"
          - label: "Paragraphs"
            name: "paragraphs"
            widget: "list"
            fields:
              - { label: "Text", name: "text", widget: "string" }
          - label: "Image"
            name: "image"
            widget: "image"
          - label: "Alt Text"
            name: "alt"
            widget: "string"
      - label: "Upcoming Concerts"
        name: "concerts"
        file: "content/upcoming-concerts.md"
        fields:
          - label: "Concerts"
            name: "concerts"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date and Time", name: "datetime", widget: "datetime" }
              - { label: "Address", name: "address", widget: "string" }
              - { label: "Ticket Link", name: "ticketLink", widget: "string" }

      - label: "Recordings"
        name: "recordings"
        file: "content/recordings.md"
        fields:
          - label: "Recordings List"
            name: "recordings"
            widget: "list"
            fields:
              - label: "Type"
                name: "type"
                widget: "select"
                options:
                  - "Video URL"
                  - "Image Link"
              - label: "URL"
                name: "url"
                widget: "string"
              - label: "Header"
                name: "header"
                widget: "string"
              - label: "Image (required for Image Links only)"
                name: "image"
                widget: "image"
                hint: "Required only for Image Links."
                required: false

      - label: "Gallery"
        name: "gallery"
        file: "content/gallery.md"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
                allow_multiple: false
              - label: "Alt Text"
                name: "alt"
                widget: "string"
