backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Biography"
        name: "biography"
        file: "content/biography.md"
        fields:
          - label: "Header"
            name: "header"
            widget: "string"
          - label: "Paragraphs"
            name: "paragraphs"
            widget: "list"
            fields:
              - { label: "Text", name: "text", widget: "string" }
      - label: "Upcoming Concerts"
        name: "concerts"
        file: "content/upcoming-concerts.md"
        fields:
          - label: "Concerts"
            name: "concerts"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date and Time", name: "datetime", widget: "datetime" }
              - { label: "Address", name: "address", widget: "string" }
              - { label: "Ticket Link", name: "ticketLink", widget: "string" }
      - label: "Gallery"
        name: "gallery"
        file: "content/gallery.md"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
                allow_multiple: false
                required: true
              - label: "Alt Text"
                name: "alt"
                widget: "string"
                required: true
